// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2acGVVd6cemS3_9uKajRyH_Oh8qkNPdY',
    appId: '1:66018666918:web:bf9bf6f9b8d6589d3b4767',
    messagingSenderId: '66018666918',
    projectId: 'ci-cd-test-565a4',
    authDomain: 'ci-cd-test-565a4.firebaseapp.com',
    storageBucket: 'ci-cd-test-565a4.firebasestorage.app',
    measurementId: 'G-3GVP9NLZGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0_BjBYsPOV6wB2_ft-WflfRdqeLLhwBw',
    appId: '1:66018666918:android:20460df1f06e3ffd3b4767',
    messagingSenderId: '66018666918',
    projectId: 'ci-cd-test-565a4',
    storageBucket: 'ci-cd-test-565a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0vxdEGkk4TDild8YppOVKwoA7MZe8mlY',
    appId: '1:66018666918:ios:f8454efdee32bf2a3b4767',
    messagingSenderId: '66018666918',
    projectId: 'ci-cd-test-565a4',
    storageBucket: 'ci-cd-test-565a4.firebasestorage.app',
    iosBundleId: 'com.example.ciCdTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0vxdEGkk4TDild8YppOVKwoA7MZe8mlY',
    appId: '1:66018666918:ios:f8454efdee32bf2a3b4767',
    messagingSenderId: '66018666918',
    projectId: 'ci-cd-test-565a4',
    storageBucket: 'ci-cd-test-565a4.firebasestorage.app',
    iosBundleId: 'com.example.ciCdTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2acGVVd6cemS3_9uKajRyH_Oh8qkNPdY',
    appId: '1:66018666918:web:728efdacb32895573b4767',
    messagingSenderId: '66018666918',
    projectId: 'ci-cd-test-565a4',
    authDomain: 'ci-cd-test-565a4.firebaseapp.com',
    storageBucket: 'ci-cd-test-565a4.firebasestorage.app',
    measurementId: 'G-7DJRTV3FWL',
  );
}
